#!/usr/bin/env python3

import argparse
import os
import numpy as np
import xesmf as xe
from netCDF4 import Dataset

def parseCommandLine():
    parser = argparse.ArgumentParser(description=("Generate regrid weight file by xesmf"))
    parser.add_argument("regridder_file_path", help=(
                "path to store the regridder file generated by xesmf"))
    parser.add_argument("--target_grid_path",required=True, help=(
                "path of the target grid file (e.g., MOM)"))
    parser.add_argument("--source_grid_path", required=True, help=(
                "path of the source grid file (e.g., L4 SST from OSTIA)"))
    args = parser.parse_args()
    print(args)
    return args

def main(args):

    # MOM latlon grids as output grids
    fn_grd_out = os.path.abspath(args.target_grid_path)
    f = Dataset(fn_grd_out)
    lat2d_grd_out = f.variables['lat'][:]
    lon2d_grd_out = f.variables['lon'][:]
    f.close()

    print("lat2d_grd_out: shape, min, max=",lat2d_grd_out.shape, np.min(lat2d_grd_out), np.max(lat2d_grd_out))
    print("lon2d_grd_out: shape, min, max=",lon2d_grd_out.shape, np.min(lon2d_grd_out), np.max(lon2d_grd_out))

    # L4 latlon grids as input grids
    fn_grd_in = os.path.abspath(args.source_grid_path)
    f = Dataset(fn_grd_in)
    lat1d_grd_in = f.variables['lat'][:]
    lon1d_grd_in = f.variables['lon'][:]
    f.close()

    print("lat1d_grd_in: shape, min, max=",lat1d_grd_in.shape, np.min(lat1d_grd_in), np.max(lat1d_grd_in))
    print("lon1d_grd_in: shape, min, max=",lon1d_grd_in.shape, np.min(lon1d_grd_in), np.max(lon1d_grd_in))

    # generate the regridder 
    grd_in = {"lon": lon1d_grd_in, "lat": lat1d_grd_in}  
    grd_out = {"lon": lon2d_grd_out, "lat": lat2d_grd_out}
    interp_method = "bilinear"
    periodic = True
    regridder = xe.Regridder(grd_in, grd_out, interp_method, periodic=periodic)
  
    fn_regridder_out = os.path.abspath(args.regridder_file_path)
    print("write regrid info into the file: ", fn_regridder_out)
    regridder.filename = fn_regridder_out
    regridder.to_netcdf()

    print(regridder)

    return None

if __name__ == '__main__':
    args = parseCommandLine()
    main(args)

