# Hello, Steve.Penny
# FMKMF_F90 set to ftn -I/opt/cray/netcdf/4.2.0/pgi/119/include
# FMKMF_SFTAG not set: using f90
# FMKMF_SPATH set to .:../../mom4/common:../../mom4/obs:../../common
# FMKMF_LINKOPTS set to -L/opt/cray/netcdf/4.2.0/pgi/119/lib -lnetcdf -lnetcdff
# Main program is letkf.f90 
# process_fsource called with arg letkf.f90 
# letkf.f90 Uses Module common
# letkf.f90 Uses Module common_mpi
# letkf.f90 Uses Module common_mom4
# letkf.f90 Uses Module common_mpi_mom4
# letkf.f90 Uses Module common_letkf
# letkf.f90 Uses Module letkf_obs
# letkf.f90 Uses Module letkf_tools
# letkf.f90 Uses Module params_letkf
# letkf.f90 Uses Module params_model
# letkf.f90 Uses Module params_obs
# Full list of modules in letkf.f90: common common_mpi common_mom4 common_mpi_mom4 common_letkf letkf_obs letkf_tools params_letkf params_model params_obs 
# Uses common which is in ../../common/common.f90
# process_fsource called with arg ../../common/common.f90 
# Full list of modules in ../../common/common.f90:  
# Uses common_mpi which is in ../../common/common_mpi.f90
# process_fsource called with arg ../../common/common_mpi.f90 
# Full list of modules in ../../common/common_mpi.f90:  
# Uses common_mom4 which is in ../../mom4/common/common_mom4.f90
# process_fsource called with arg ../../mom4/common/common_mom4.f90 
# ../../mom4/common/common_mom4.f90 Uses Module common
# ../../mom4/common/common_mom4.f90 Uses Module params_model
# ../../mom4/common/common_mom4.f90 Uses Module vars_model
# ../../mom4/common/common_mom4.f90 Uses Module params_letkf
# ../../mom4/common/common_mom4.f90 Uses Module netcdf
# ../../mom4/common/common_mom4.f90 Uses Module netcdf
# ../../mom4/common/common_mom4.f90 Uses Module netcdf
# ../../mom4/common/common_mom4.f90 Uses Module netcdf
# ../../mom4/common/common_mom4.f90 Uses Module netcdf
# ../../mom4/common/common_mom4.f90 Uses Module netcdf
# Full list of modules in ../../mom4/common/common_mom4.f90: common params_model vars_model params_letkf netcdf netcdf netcdf netcdf netcdf netcdf 
# Uses common which is in ../../common/common.f90
# ../../common/common.f90 already in list
# Uses params_model which is in ./params_model.f90
# process_fsource called with arg ./params_model.f90 
# Full list of modules in ./params_model.f90:  
# Uses vars_model which is in ./vars_model.f90
# process_fsource called with arg ./vars_model.f90 
# ./vars_model.f90 Uses Module common
# ./vars_model.f90 Uses Module params_model
# Full list of modules in ./vars_model.f90: common params_model 
# Uses common which is in ../../common/common.f90
# ../../common/common.f90 already in list
# Uses params_model which is in ./params_model.f90
# ./params_model.f90 already in list
# Uses params_letkf which is in ./params_letkf.f90
# process_fsource called with arg ./params_letkf.f90 
# ./params_letkf.f90 Uses Module common
# Full list of modules in ./params_letkf.f90: common 
# Uses common which is in ../../common/common.f90
# ../../common/common.f90 already in list
# Uses common_mpi_mom4 which is in ../../mom4/common/common_mpi_mom4.f90
# process_fsource called with arg ../../mom4/common/common_mpi_mom4.f90 
# ../../mom4/common/common_mpi_mom4.f90 Uses Module common
# ../../mom4/common/common_mpi_mom4.f90 Uses Module common_mpi
# ../../mom4/common/common_mpi_mom4.f90 Uses Module common_mom4
# Full list of modules in ../../mom4/common/common_mpi_mom4.f90: common common_mpi common_mom4 
# Uses common which is in ../../common/common.f90
# ../../common/common.f90 already in list
# Uses common_mpi which is in ../../common/common_mpi.f90
# ../../common/common_mpi.f90 already in list
# Uses common_mom4 which is in ../../mom4/common/common_mom4.f90
# ../../mom4/common/common_mom4.f90 already in list
# Uses common_letkf which is in ../../common/common_letkf.f90
# process_fsource called with arg ../../common/common_letkf.f90 
# ../../common/common_letkf.f90 Uses Module common
# ../../common/common_letkf.f90 Uses Module common_mtx
# ../../common/common_letkf.f90 Uses Module params_letkf
# Full list of modules in ../../common/common_letkf.f90: common common_mtx params_letkf 
# Uses common which is in ../../common/common.f90
# ../../common/common.f90 already in list
# Uses common_mtx which is in ../../common/common_mtx.f90
# process_fsource called with arg ../../common/common_mtx.f90 
# ../../common/common_mtx.f90 Uses Module common
# Full list of modules in ../../common/common_mtx.f90: common 
# Uses common which is in ../../common/common.f90
# ../../common/common.f90 already in list
# Uses params_letkf which is in ./params_letkf.f90
# ./params_letkf.f90 already in list
# Uses letkf_obs which is in ./letkf_obs.f90
# process_fsource called with arg ./letkf_obs.f90 
# ./letkf_obs.f90 Uses Module common
# ./letkf_obs.f90 Uses Module common_mpi
# ./letkf_obs.f90 Uses Module common_mom4
# ./letkf_obs.f90 Uses Module common_obs_mom4
# ./letkf_obs.f90 Uses Module common_mpi_mom4
# ./letkf_obs.f90 Uses Module common_letkf
# ./letkf_obs.f90 Uses Module params_letkf
# ./letkf_obs.f90 Uses Module params_obs
# ./letkf_obs.f90 Uses Module vars_obs
# Full list of modules in ./letkf_obs.f90: common common_mpi common_mom4 common_obs_mom4 common_mpi_mom4 common_letkf params_letkf params_obs vars_obs 
# Uses common which is in ../../common/common.f90
# ../../common/common.f90 already in list
# Uses common_mpi which is in ../../common/common_mpi.f90
# ../../common/common_mpi.f90 already in list
# Uses common_mom4 which is in ../../mom4/common/common_mom4.f90
# ../../mom4/common/common_mom4.f90 already in list
# Uses common_obs_mom4 which is in ../../mom4/common/common_obs_mom4.f90
# process_fsource called with arg ../../mom4/common/common_obs_mom4.f90 
# ../../mom4/common/common_obs_mom4.f90 Uses Module common
# ../../mom4/common/common_obs_mom4.f90 Uses Module common_mom4
# ../../mom4/common/common_obs_mom4.f90 Uses Module params_obs
# Full list of modules in ../../mom4/common/common_obs_mom4.f90: common common_mom4 params_obs 
# Uses common which is in ../../common/common.f90
# ../../common/common.f90 already in list
# Uses common_mom4 which is in ../../mom4/common/common_mom4.f90
# ../../mom4/common/common_mom4.f90 already in list
# Uses params_obs which is in ../../mom4/obs/params_obs.f90
# process_fsource called with arg ../../mom4/obs/params_obs.f90 
# ../../mom4/obs/params_obs.f90 Uses Module common
# Full list of modules in ../../mom4/obs/params_obs.f90: common 
# Uses common which is in ../../common/common.f90
# ../../common/common.f90 already in list
# Uses common_mpi_mom4 which is in ../../mom4/common/common_mpi_mom4.f90
# ../../mom4/common/common_mpi_mom4.f90 already in list
# Uses common_letkf which is in ../../common/common_letkf.f90
# ../../common/common_letkf.f90 already in list
# Uses params_letkf which is in ./params_letkf.f90
# ./params_letkf.f90 already in list
# Uses params_obs which is in ../../mom4/obs/params_obs.f90
# ../../mom4/obs/params_obs.f90 already in list
# Uses vars_obs which is in ../../mom4/obs/vars_obs.f90
# process_fsource called with arg ../../mom4/obs/vars_obs.f90 
# ../../mom4/obs/vars_obs.f90 Uses Module common
# Full list of modules in ../../mom4/obs/vars_obs.f90: common 
# Uses common which is in ../../common/common.f90
# ../../common/common.f90 already in list
# Uses letkf_tools which is in ./letkf_tools.f90
# process_fsource called with arg ./letkf_tools.f90 
# ./letkf_tools.f90 Uses Module common
# ./letkf_tools.f90 Uses Module common_mpi
# ./letkf_tools.f90 Uses Module common_mom4
# ./letkf_tools.f90 Uses Module common_mpi_mom4
# ./letkf_tools.f90 Uses Module common_letkf
# ./letkf_tools.f90 Uses Module letkf_obs
# ./letkf_tools.f90 Uses Module letkf_local
# ./letkf_tools.f90 Uses Module params_letkf
# Full list of modules in ./letkf_tools.f90: common common_mpi common_mom4 common_mpi_mom4 common_letkf letkf_obs letkf_local params_letkf 
# Uses common which is in ../../common/common.f90
# ../../common/common.f90 already in list
# Uses common_mpi which is in ../../common/common_mpi.f90
# ../../common/common_mpi.f90 already in list
# Uses common_mom4 which is in ../../mom4/common/common_mom4.f90
# ../../mom4/common/common_mom4.f90 already in list
# Uses common_mpi_mom4 which is in ../../mom4/common/common_mpi_mom4.f90
# ../../mom4/common/common_mpi_mom4.f90 already in list
# Uses common_letkf which is in ../../common/common_letkf.f90
# ../../common/common_letkf.f90 already in list
# Uses letkf_obs which is in ./letkf_obs.f90
# ./letkf_obs.f90 already in list
# Uses letkf_local which is in ./letkf_local.f90
# process_fsource called with arg ./letkf_local.f90 
# ./letkf_local.f90 Uses Module common
# ./letkf_local.f90 Uses Module common_mpi
# ./letkf_local.f90 Uses Module common_mom4
# ./letkf_local.f90 Uses Module common_mpi_mom4
# ./letkf_local.f90 Uses Module common_letkf
# ./letkf_local.f90 Uses Module letkf_obs
# ./letkf_local.f90 Uses Module params_letkf
# Full list of modules in ./letkf_local.f90: common common_mpi common_mom4 common_mpi_mom4 common_letkf letkf_obs params_letkf 
# Uses common which is in ../../common/common.f90
# ../../common/common.f90 already in list
# Uses common_mpi which is in ../../common/common_mpi.f90
# ../../common/common_mpi.f90 already in list
# Uses common_mom4 which is in ../../mom4/common/common_mom4.f90
# ../../mom4/common/common_mom4.f90 already in list
# Uses common_mpi_mom4 which is in ../../mom4/common/common_mpi_mom4.f90
# ../../mom4/common/common_mpi_mom4.f90 already in list
# Uses common_letkf which is in ../../common/common_letkf.f90
# ../../common/common_letkf.f90 already in list
# Uses letkf_obs which is in ./letkf_obs.f90
# ./letkf_obs.f90 already in list
# Uses params_letkf which is in ./params_letkf.f90
# ./params_letkf.f90 already in list
# Uses params_letkf which is in ./params_letkf.f90
# ./params_letkf.f90 already in list
# Uses params_letkf which is in ./params_letkf.f90
# ./params_letkf.f90 already in list
# Uses params_model which is in ./params_model.f90
# ./params_model.f90 already in list
# Uses params_obs which is in ../../mom4/obs/params_obs.f90
# ../../mom4/obs/params_obs.f90 already in list

# ------------------Macro-Defs---------------------
F90=ftn -I/opt/cray/netcdf/4.2.0/pgi/119/include 

# -------------------End-macro-Defs---------------------------

# Here is the link step 
letkf:common.o common_mpi.o params_model.o vars_model.o params_letkf.o common_mom4.o common_mpi_mom4.o common_mtx.o common_letkf.o params_obs.o common_obs_mom4.o vars_obs.o letkf_obs.o letkf_local.o letkf_tools.o letkf.o 
	 $(F90) -o letkf common.o common_mpi.o params_model.o vars_model.o params_letkf.o common_mom4.o common_mpi_mom4.o common_mtx.o common_letkf.o params_obs.o common_obs_mom4.o vars_obs.o letkf_obs.o letkf_local.o letkf_tools.o letkf.o -L/opt/cray/netcdf/4.2.0/pgi/119/lib -lnetcdf -lnetcdff 

# Here are the compile steps
 
common.o:../../common/common.f90  
	 $(F90) -c ../../common/common.f90 

common_mpi.o:../../common/common_mpi.f90  
	 $(F90) -c ../../common/common_mpi.f90 

params_model.o:./params_model.f90  
	 $(F90) -c ./params_model.f90 

vars_model.o:./vars_model.f90 common.o params_model.o 
	 $(F90) -c ./vars_model.f90 

params_letkf.o:./params_letkf.f90 common.o 
	 $(F90) -c ./params_letkf.f90 

common_mom4.o:../../mom4/common/common_mom4.f90 common.o params_model.o vars_model.o params_letkf.o 
	 $(F90) -c ../../mom4/common/common_mom4.f90 

common_mpi_mom4.o:../../mom4/common/common_mpi_mom4.f90 common.o common_mpi.o common_mom4.o 
	 $(F90) -c ../../mom4/common/common_mpi_mom4.f90 

common_mtx.o:../../common/common_mtx.f90 common.o 
	 $(F90) -c ../../common/common_mtx.f90 

common_letkf.o:../../common/common_letkf.f90 common.o common_mtx.o params_letkf.o 
	 $(F90) -c ../../common/common_letkf.f90 

params_obs.o:../../mom4/obs/params_obs.f90 common.o 
	 $(F90) -c ../../mom4/obs/params_obs.f90 

common_obs_mom4.o:../../mom4/common/common_obs_mom4.f90 common.o common_mom4.o params_obs.o 
	 $(F90) -c ../../mom4/common/common_obs_mom4.f90 

vars_obs.o:../../mom4/obs/vars_obs.f90 common.o 
	 $(F90) -c ../../mom4/obs/vars_obs.f90 

letkf_obs.o:./letkf_obs.f90 common.o common_mpi.o common_mom4.o common_obs_mom4.o common_mpi_mom4.o common_letkf.o params_letkf.o params_obs.o vars_obs.o 
	 $(F90) -c ./letkf_obs.f90 

letkf_local.o:./letkf_local.f90 common.o common_mpi.o common_mom4.o common_mpi_mom4.o common_letkf.o letkf_obs.o params_letkf.o 
	 $(F90) -c ./letkf_local.f90 

letkf_tools.o:./letkf_tools.f90 common.o common_mpi.o common_mom4.o common_mpi_mom4.o common_letkf.o letkf_obs.o letkf_local.o params_letkf.o 
	 $(F90) -c ./letkf_tools.f90 

letkf.o:letkf.f90 common.o common_mpi.o common_mom4.o common_mpi_mom4.o common_letkf.o letkf_obs.o letkf_tools.o params_letkf.o params_model.o params_obs.o 
	 $(F90) -c letkf.f90 
# This entry allows you to type " make clean " to get rid of
# all object and module files 
clean:
	rm -f -r f_{files,modd}* *.o *.mod *.M *.d V*.inc *.vo \
	V*.f *.dbg album F.err
  
