######################################################################
SRC=cmbDLstPs4nc_synth.c
OBJ=$(SRC:.c=.o)
NETCDF=/opt/cray/netcdf/4.2.0/intel/120
#HDF5=/opt/cray/hdf5/1.8.8/intel/120
LBO=$(NETCDF)/lib/libnetcdf.a 
INC=-I$(NETCDF)/include
CFLAG=
LDFLAG=
CC=cc
TARGET=cmbDLstPs4nc_synth

.c.o:
	$(CC) $(CFLAG) $(INC) -c $<

$(TARGET): $(OBJ) $(LBO)
	$(CC) $(LDFLAG) -o $(TARGET) $(OBJ) $(LBO) -lm
