######################################################################
SRC=extDysP4nc.c
OBJ=$(SRC:.c=.o)
NETCDF=/opt/cray/netcdf/4.2.0/intel/120
LBO=~/lib/TUtl.a $(NETCDF)/lib/libnetcdf.a
INC=-I$(NETCDF)/include
CFLAG=
LDFLAG=
CC=cc
TARGET=extDysP4nc

.c.o:
	$(CC) $(CFLAG) $(INC) -c $<

$(TARGET): $(OBJ) $(LBO)
	$(CC) $(LDFLAG) -o $(TARGET) $(OBJ) $(LBO) -lm
