######################################################################
SRC=incDate.c
OBJ=$(SRC:.c=.o)
LBO=~/SFLUX/Time/TUtl.a
INC=-I$(NETCDF)/include
CFLAG=
LDFLAG=
CC=cc
TARGET=incDate

.c.o:
	$(CC) $(CFLAG) $(INC) -c $<

$(TARGET): $(OBJ) $(LBO)
	$(CC) $(LDFLAG) -o $(TARGET) $(OBJ) $(LBO) -lm
