#!/bin/bash

F90=ftn
F90_OPT='-O2'
#STEVE: -mcmodel=medium needed for large model grid sizes (e.g. higher than 1 degree resolution of om3_core3)
# explanation of -mcmodel=medium and -shared-intel: http://software.intel.com/en-us/forums/showthread.php?t=43717#18089
F90_INLINE= #"-Q -qinline"
F90_DEBUG= #'-check all -debug minimal -g -traceback'
#F90_DEBUG='-check all -debug minimal -g -traceback' #'-g -qfullpath -v -C -qsigtrap=xl__trcedump' # -qflttrap=en:nanq -qsigtrap'
F90_IEEE='-fltconsistency' #'-Kieee' #'-fltconsistency'
F90_OBJECT_FLAG='-c' #STEVE: for some reason, mpxlf doesn't use -c, but rather -g
BLAS=1
F90_FPP='-fpp'
BLAS_DIR=${CRAY_LIBSCI_PREFIX_DIR}
BLAS_LIBS="-lsci_intel -lsci_intel_mp"
#BLAS_LIBS="-lsci_cray -lsci_cray_mp"

#   Options that Improve Run-Time Performance
#   The following command line options can be used to increase the run-time performance of code generated by the Intel(R) Fortran Compiler:
#
#   On systems using IA-32 architecture and systems using Intel(R)  64  architecture:  
#   -ax<processor>,  -ftz,  -ip,  -ipo,  -march=<processor>,
#   -mtune=<processor>, -O[n], -openmp, -parallel, -prof-gen, -prof-use, -x<processor>.
