######################################################################
SRC=mkEvNc4r.c
OBJ=$(SRC:.c=.o)
NCDF=$(NETCDF)/lib/libnetcdf.a
INC=-I$(NETCDF)/include
CC=icc
#CFLAG=-qarch=auto -qmaxmem=-1
CFLAG=
LDFLAG=
TARGET=mkEvNc4r

$(TARGET): $(OBJ) $(LBO)
	$(CC) $(LDFLAG) -o $(TARGET) $(OBJ) $(NCDF) -lm

.c.o:
	$(CC) $(CFLAG) $(INC) -c $<
