name: build_gfortran

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Debug

jobs:
  cmake_build:
    strategy:
      matrix: 
        model: [mom6]
      fail-fast: false
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: "install mpi, netcdf, hdf5"
      run: |
           sudo apt-get update
           sudo apt install mpich   
           sudo apt install libnetcdf-dev libnetcdff-dev netcdf-bin
           sudo apt install hdf5-tools libhdf5-dev

    - name: "check version and envs"
      run: |
           echo "===============================" && nf-config --all
           echo "===============================" && nc-config --all
           echo "===============================" && h5fc -showconfig && h5fc -show test.f90
           echo "===============================" && gcc -v
           echo "===============================" && gfortran -v
           echo "===============================" && mpif90 -v
           echo "===============================" && ulimit -a
           echo "===============================" && pwd

    - name: "cmake build for each model"
      run: |
           echo "===================================="
           echo "cmake build for ${{matrix.model}}"
           echo ""
           echo "===================================="
           cmake -B ${{github.workspace}}/build_ocnletkf -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_Fortran_COMPILER=gfortran -DSOLO_BUILD=ON -DMODEL=${{matrix.model}}
           cmake --build ${{github.workspace}}/build_ocnletkf --config ${{env.BUILD_TYPE}}


  sh_build:
    strategy:
      matrix: 
        model: [mom6_dynamic, mom6, mom4, roms, nemo, cice5, sis, hycom, hycom_nrl]
      fail-fast: false
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: "install mpi, netcdf, hdf5"
      run: |
           sudo apt-get update
           sudo apt install mpich   
           sudo apt install libnetcdf-dev libnetcdff-dev netcdf-bin
           sudo apt install hdf5-tools libhdf5-dev

    - name: "check version and envs"
      run: |
           echo "===============================" && nf-config --all
           echo "===============================" && nc-config --all
           echo "===============================" && h5fc -showconfig && h5fc -show test.f90
           echo "===============================" && gcc -v
           echo "===============================" && gfortran -v
           echo "===============================" && mpif90 -v
           echo "===============================" && ulimit -a
           echo "===============================" && pwd

    - name: "build/make_*.sh for model"
      run: |
           echo "===================================="
           echo "build/make_*.sh for ${{matrix.model}}"
           echo ""
           echo "===================================="
           cd ${{github.workspace}}/build && pwd
           rm -rf build_letkf/*
           rm -rf build_obsop/*
           bash -xe make_obsop.${{matrix.model}}.sh
           bash -xe make_letkf.${{matrix.model}}.sh

