name: get_data

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Debug

jobs:
  get_data:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: "install packages"
      run: |
           sudo apt-get update
           sudo apt install wget

    - name: "check version and envs"
      run: |
           wget --version

    - name: "check: get_l2b_smap_jpl.py"
      run: |
           cd ${{github.workspace}}/utils/obs_proc/level-2
           pwd
           PYTHONPATH=../../pycommon ./get_l2b_smap_jpl.py --start_date 20220101 --end_date 20220102 --outdir ./ --topdir_name test_l2_sss --skip_remote_check --verbose --log
           ls -al 
           ls -al ./test_l2_sss/2022/202201/20220101/
           rm -rf test_l2_sss
           ls -al

    - name: "check: get_l3_smap_jpl.py"
      run: |
           cd ${{github.workspace}}/utils/obs_proc/level-3
           pwd
           PYTHONPATH=../../pycommon ./get_l3_smap_jpl.py --start_date 20220101 --end_date 20220102 --outdir ./ --topdir_name test_l3_sss --skip_remote_check --verbose --log
           ls -al 
           ls -al ./test_l3_sss/2022/202201/20220101/
           rm -rf test_l3_sss
           ls -al
 
    - name: "check: get_l2p_ghrsst_geostationary.py"
      run: |
           cd ${{github.workspace}}/utils/obs_proc/level-2
           pwd
           PYTHONPATH=../../pycommon ./get_l2p_ghrsst_geostationary.py --start_date 20220110 --end_date 20220111 --sis ABI_G17 --outdir ./ --topdir_name test_l2p_sst --skip_remote_check  --get_nav_file --verbose --log
           ls -al 
           ls -al ./test_l2p_sst/ABI_G17/2022/202201/20220111/
           ls -al ./test_l2p_sst/ABI_G17/nav
           rm -rf test_l2p_sst

    - name: "check: get_monthly_woa18.py"
      run: |
           cd ${{github.workspace}}/utils/obs_proc/woa
           pwd
           PYTHONPATH=../../pycommon ./get_monthly_woa18.py test_sal_woa18 --start_month 1 --end_month 2 --res 5 --dvar salinity --verbose
           PYTHONPATH=../../pycommon ./get_monthly_woa18.py test_temp_woa18 --start_month 1 --end_month 2 --res 5 --dvar temperature --verbose
           ls -al 
           ls -al ./test_sal_woa18
           ls -al ./test_temp_woa18


    - name: "check: get_l4_sss_esacci.py"
      run: |
           cd ${{github.workspace}}/utils/obs_proc/level-4
           pwd
           PYTHONPATH=../../pycommon ./get_l4_sss_esacci.py --topdir_name test_l4sss_esacci --start_date 20180101 --end_date 20180102 --log --verbose
           ls -al 
           ls -al ./test_l4sss_esacci/2018/201801/20180102
 
    - name: "check: get_l4_sst_ostia_v1.py"
      run: |
           cd ${{github.workspace}}/utils/obs_proc/level-4
           pwd
           PYTHONPATH=../../pycommon  ./get_l4_sst_ostia_v1.py --topdir_name test_l4_sst_ostia_v1 --start_date 20190101 --start_date 20180101 --end_date 20180102 --log --verbose
           ls -al 
           ls -al ./test_l4_sst_ostia_v1/2018/201801/20180102
 
